card_No~wI_No~sLA_TAT
card_No~wI_No
card_No~wI_No
card_No~wI_No~dDMMYYYY
card_No~wI_No
card_No~wI_No~cancellationReason
card_No~wI_No~sub_Process_Name~sLA_TAT
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No
card_No~wI_No~amount
card_No~wI_No~dDMMYYYY
card_No~wI_No~sub_Process_Name~sLA_TAT
card_No~wI_No~sub_Process_Name~sLA_TAT
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name~dDMMYYYY
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name~dDMMYYYY
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name
card_No~wI_No~sub_Process_Name~dDMMYYYY
card_No~wI_No~sub_Process_Name
